import { handleError } from "@/utils/handleError.ts";
import { NextFunction, Request, Response } from "express";

export const createDocumentMetadata = async (req: Request, res: Response, next: NextFunction) => {
    try {

    } catch (error) {
        handleError(error, res, next);
    }
}

export const getAllDocumentsMetadata = async (req: Request, res: Response, next: NextFunction) => {
    try {

    } catch (error) {
        handleError(error, res, next);
    }
}

export const getDocumentMetadataById = async (req: Request, res: Response, next: NextFunction) => {
    try {

    } catch (error) {
        handleError(error, res, next);
    }
}

export const getDocumentMetadataByName = async (req: Request, res: Response, next: NextFunction) => {
    try {

    } catch (error) {
        handleError(error, res, next);
    }
}

export const updateDocumentMetadata = async (req: Request, res: Response, next: NextFunction) => {
    try {

    } catch (error) {
        handleError(error, res, next);
    }
}

export const deleteDocumentMetadata = async (req: Request, res: Response, next: NextFunction) => {
    try {

    } catch (error) {
        handleError(error, res, next);
    }
}

export const getDocument = async (req: Request, res: Response, next: NextFunction) => {
    try {

    } catch (error) {
        handleError(error, res, next);
    }
}

export const uploadDocument = async (req: Request, res: Response, next: NextFunction) => {
    try {

    } catch (error) {
        handleError(error, res, next);
    }
}